### ISSUE TITLE
Dimension mismatch in "Import spots from label images"

### ISSUE THREAD

**Issue by ilyasdc** [mastodon-sc/mastodon-deep-lineage#119]
Hello,

Thank you for your mastodon and especially your plugin for importing label images which exactly fits what I'd like to do.
Unfortunately it doesnt' seem to work in my case, the dimensions don't seem to be correctly interpreted:
![Screenshot From 2024-11-12 16-01-38](https://github.com/user-attachments/assets/0af2f078-a751-4326-a08e-3496322b4095)

- One file is a standard ImageJ tif the other one a OME TTIF. 
- Both files are opened virtually. 
- The dimensions of the metadata is not initially the same but I changed it in the image->properties menu as shown by the screenshot. 
- Since I saw "imageJ2" was involved in  the error message I tried to open the files withSCIFIO but the error is the same success. 

Happy to provide more information.
(the current workaround is to use the label as an extra channel, but even then it seems to struggle for 600 timepoints + several thousand labels/timepoint. I've seen that there was some discusions with the non-optimized status of this function so I guess it's expected)

**Comment by stefanhahmann** [comment]
Thanks for reaching out.

Would you mind to provide reduced versions of the image data that you used with just two timepoints for each image (and perhaps and if possible a reduced resolution, e.g. XxYxZxt = 464x464x1x2)? For testing, it would be good to have one version of both the "Standard ImageJ tif" and the "OME TIFF".

Do I understand it correctly that you actually have 2-dimensional data, i.e. 4646x4646 pixel in one 2d-slice over 600 timepoints?

I am asking, since I did not actually test, if the import works for 2D data.

**Comment by ilyasdc** [comment]
> Thanks for reaching out.
> 
> Would you mind to provide reduced versions of the image data that you used with just two timepoints for each image (and perhaps and if possible a reduced resolution, e.g. XxYxZxt = 464x464x1x2)? For testing, it would be good to have one version of both the "Standard ImageJ tif" and the "OME TIFF".
> 
Please find the files in tif and OME-TIFF format (link expires in 24h) https://wormhole.app/M5ybA#YDmNzfCbeEsZDcyj-3WR-w : For each tiff format there is one file for the bright-field images, one for the label images.
> Do I understand it correctly that you actually have 2-dimensional data, i.e. 4646x4646 pixel in one 2d-slice over 600 timepoints?
> 
> I am asking, since I did not actually test, if the import works for 2D data.

Yes, you are correct. It's a 2D+t dataset.

**Comment by stefanhahmann** [comment]
> Please find the files in tif and OME-TIFF format (link expires in 2 weeks) https://file.io/TyfC7QVsyIMV : For each tiff format there is one file for the bright-field images, one for the label images.

Thanks for the test data. Will have a look at it.

**Comment by stefanhahmann** [comment]
@ilyasdc 

Thanks again for reporting the bug and providing suitable test data.

We have added a bugfix and published a new release (https://github.com/mastodon-sc/mastodon-deep-lineage/releases/tag/mastodon-deep-lineage-0.3.4). It is already uploaded on the FIJI update site.

With this bugfix, I was able to create the spots from the segmentation: 
![grafik](https://github.com/user-attachments/assets/97093fa0-a28f-4094-b7d9-6e4cf59d5764)

The non-OME tiffs worked a little bit better, since for them in FIJI/Image the dimension in the image properties were set correctly: 
![grafik](https://github.com/user-attachments/assets/7e13c834-bc46-4e50-996e-3b3f0c97931a)

Please do note that the position of the import command in Mastodon has moved to `File -> Import -> Import Spots from Label Image`

In the case of your data, I recommend to leave the option "link spots with same id in consecutive timepoints" unchecked.

To link to spots between timepoints, I recommend using the Linker that commes with Mastodon: `Plugins > Tracking > Linking`

For the import, you may also watch the youtube video, where I explain the process a little bit: https://www.youtube.com/watch?v=kQakhhBnl_8

**Comment by ilyasdc** [comment]
Hello again @stefanhahmann,

Thank you again for your time. It seems that the script incorrectly sets the z coordinate for to the voxel size as can be seen in the table:
![image](https://github.com/user-attachments/assets/1ea3acda-cd7f-44dd-9d3d-0a3d116b883b)
 
When one then selects a track/spot the z change and the image becomes invisible.

For the time being I  wrote a primitive script based on the docs to reset it after the mastodon file has been generated, but I'm sure it can be made better and faster !
```python
#@ Context context
# This script takes a mastodon file and zeroes-out all the z positions of the spots 
from org.mastodon.mamut import Mamut
import os

existingMastodonFile = 'xxx.mastodon'
mamut = Mamut.open( existingMastodonFile, context )
mamut.info()

#
## Print some info on the model before we remove spots.
#logger.info( "Before:\n" )
#mamut.info()
#

print("Start")

it = mamut.getModel().getGraph().vertices().iterator()
while it.hasNext():
	v = it.next()
	x,y,z = v.getDoublePosition(0),v.getDoublePosition(1),v.getDoublePosition(2)
	# set z to 0
	v.setPosition((x,y,0))
print("Done")


mamut.saveAs('xxx_fixed.mastodon')
```

PS: is there a way to access the current running mamut instance without using the "open" method ?

**Comment by stefanhahmann** [comment]
> Thank you again for your time. It seems that the script incorrectly sets the z coordinate for to the voxel size as can be seen in the table:
> When one then selects a track/spot the z change and the image becomes invisible.

Thanks for reporting this. The z-coordinate was indeed falsely set to `1` during the import. I was not aware that this would cause trouble with the BigDataViewer. `z=0` is nevertheless anyway the better choice for 2D+t images.

> For the time being I wrote a primitive script based on the docs to reset it after the mastodon file has been generated, but I'm sure it can be made better and faster !

The workaround that you presented is actually really nice. It should however now not be necessary anymore, since I just uploaded a version with a bugfix for this

> PS: is there a way to access the current running mamut instance without using the "open" method ?

Good question. I am afraid I do not know the answer. @tinevez might know. But I guess with the bugfix, you do not need to access the current running mamut instance anymore?

**Comment by ilyasdc** [comment]
> > Thank you again for your time. It seems that the script incorrectly sets the z coordinate for to the voxel size as can be seen in the table:
> > When one then selects a track/spot the z change and the image becomes invisible.
> 
> Thanks for reporting this. The z-coordinate was indeed falsely set to `1` during the import. I was not aware that this would cause trouble with the BigDataViewer. `z=0` is nevertheless anyway the better choice for 2D+t images.
> 
> > For the time being I wrote a primitive script based on the docs to reset it after the mastodon file has been generated, but I'm sure it can be made better and faster !
> 
> The workaround that you presented is actually really nice. It should however now not be necessary anymore, since I just uploaded a version with a bugfix for this
> 
> > PS: is there a way to access the current running mamut instance without using the "open" method ?
> 
> Good question. I am afraid I do not know the answer. @tinevez might know. But I guess with the bugfix, you do not need to access the current running mamut instance anymore?

Excellent, thank you for being so quick !

**Comment by tinevez** [comment]
> PS: is there a way to access the current running mamut instance without using the "open" method ?

Hello. Unfortunately not for the moment. There is something like this in TrackMate, but I have not found a use for ir.
